before:
  hooks:
    - go mod tidy

# Build a universal macOS binary
universal_binaries:
  - replace: false

# Build the different combination of goos/arch binaries
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X 'github.com/defenseunicorns/uds-cli/src/config.CLIVersion={{.Tag}}' -X 'github.com/defenseunicorns/zarf/src/config.ActionsCommandZarfPrefix=zarf'
    goarch:
      - amd64
      - arm64
    binary: uds

# Save the built artifacts as binaries (instead of wrapping them in a tarball)
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{- title .Os }}_{{ .Arch }}"

# generate a sha256 checksum of all release artifacts
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# generate sboms for each binary artifact
sboms:
  - artifacts: binary
    documents:
      - "sbom_{{ .ProjectName }}_{{ .Tag }}_{{- title .Os }}_{{ .Arch }}.sbom"

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

# Use the auto-generated changelog github provides
changelog:
  use: github-native

brews:
  - name: uds
    repository:
      owner: defenseunicorns
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/defenseunicorns/uds-cli"
    description: "CLI for Unicorn Delivery Service"

  # NOTE: We are using .Version instead of .Tag because homebrew has weird semver parsing rules and won't be able to
  #       install versioned releases that has a `v` character before the version number.
  - name: "uds@{{ .Version }}"
    repository:
      owner: defenseunicorns
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} versioned release {{ .Tag }}"
    homepage: "https://github.com/defenseunicorns/uds-cli"
    description: "CLI for Unicorn Delivery Service"

# Generate a GitHub release and publish the release for the tag
release:
  github:
    owner: defenseunicorns
    name: uds-cli
  prerelease: auto
  mode: append
  draft: false
