# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

fail-on-severity: "critical"
output: "json"
file: "grype-scan.json"
ignore:
  # This vulnerability does not affect UDS as we do not instantiate a rekor client
  - vulnerability: GHSA-2h5h-59f5-c5x9

  # This vulnerability does not affect UDS as we do not instantiate a rekor client
  - vulnerability: GHSA-frqx-jfcm-6jjr
