# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

fail-on-severity: "critical"
output: "table"
# file: "grype-scan.json"
ignore:
  # This vulnerability does not affect UDS as we do not make use of the CRI and
  # it appears to be a false positive hit for containerd/containerd v1.7.2, as the
  # affected range does not include v1.x.x versions and our usage of
  # containerd/containerd/v2 v2.3.2 is beyond the affected range
  # (>= 2.1.0, < 2.1.9, >= 2.2.0, < 2.2.5, >= 2.3.0, < 2.3.2)
  # this is an indirect dependency of zarf->helm->k9s->containerd/containerd
  - vulnerability: GO-2026-5064

  # This vulnerability does not affect UDS as we do not make use of the CRI and
  # it appears to be a false positive hit for containerd/containerd v1.7.2, as the
  # affected range does not include v1.x.x versions and our usage of
  # containerd/containerd/v2 v2.3.2 is beyond the affected range
  # (>= 2.1.0, < 2.1.9, >= 2.2.0, < 2.2.5, >= 2.3.0, < 2.3.2)
  # this is an indirect dependency of zarf->helm->k9s->containerd/containerd
  - vulnerability: GO-2026-5338
