# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: lint
    description: runs the linter (requires golangci-lint)
    actions:
      - cmd: golangci-lint run ./src/...

  - name: clean
    description: removes the build dir
    actions:
      - cmd: rm -rf build

  - name: local-registry
    description: run a local docker registry
    actions:
      - cmd: |
          docker run -p 5000:5000 --restart=always --name registry registry:2
