# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2023-Present The UDS Authors

tasks:
  - name: update
    description: updates the CLI docs
    actions:
      - cmd: ./hack/generate-docs.sh

  - name: test
    description: tests if the CLI docs have been modified
    actions:
      - task: update
      - cmd: ./hack/test-docs.sh
