# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2023-Present The UDS Authors

tasks:
  - name: update
    description: updates the JSON schema
    actions:
      - cmd: ./hack/generate-schema.sh

  - name: test
    description: tests if the schema has been modified
    actions:
      - task: update
      - cmd: ./hack/test-generate-schema.sh
