name: save-logs
description: "Save debug logs"

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: debug-log
        path: /tmp/uds-*.log
