name: save-logs
description: "Save debug logs"

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/uds-*.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: debug-log
        path: /tmp/uds-*.log
