name: save-logs
description: "Save debug logs"

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/uds-*.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595 # v4.1.0
      with:
        name: debug-log
        path: /tmp/uds-*.log
