name: save-logs
description: "Save debug logs"

inputs:
  suffix:
    description: 'Suffix to append to the debug log'
    required: false
    default: '

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/uds-*.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: debug-log${{ inputs.suffix }}
        path: /tmp/uds-*.log
