name: save-logs
description: "Save debug logs"

inputs:
  name:
    description: "unique name to put in log file"
    required: true

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/uds-${{ inputs.name }}.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: debug-log
        path: /tmp/uds-${{ inputs.name }}.log
