# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: setup-k3d
description: "Create a k3d cluster using the mise-managed k3d binary"

inputs:
  create-cluster:
    description: "Boolean specifying if k3d should create a cluster after installation"
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: create cluster
      if: ${{ inputs.create-cluster == 'true' }}
      run: k3d cluster delete && k3d cluster create
      shell: bash
