# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Install UDS CLI
description: installs uds-cli from brew
runs:
  using: composite
  steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@cf31444e770b9919bb21e695d66f56c39cfd3dee # main

    - name: Install UDS CLI
      shell: bash
      run: |
        brew tap defenseunicorns/tap
        brew install uds
