name: Install UDS CLI
description: installs uds-cli from brew
runs:
  using: composite
  steps:
  - name: Set up Homebrew
    uses: Homebrew/actions/setup-homebrew@a6188048cd0171bb4cac956feeff00e588500e7d # master

  - name: Install UDS CLI
    shell: bash
    run: |
      brew tap defenseunicorns/tap
      brew install uds
