# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Install UDS CLI
description: installs uds-cli from brew
runs:
  using: composite
  steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@a84a03efc108f7d05469800fd48890c1cd34a6ad # main

    - name: Install UDS CLI
      shell: bash
      run: |
        brew tap defenseunicorns/tap
        brew install uds
