# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Install UDS CLI
description: installs uds-cli from brew
runs:
  using: composite
  steps:
  - name: Set up Homebrew
    uses: Homebrew/actions/setup-homebrew@d060b6d6ebec27463122d09b327f7b8a2260fb34 # master

  - name: Install UDS CLI
    shell: bash
    run: |
      brew tap defenseunicorns/tap
      brew install uds
