# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Install UDS CLI
description: installs uds-cli from brew
runs:
  using: composite
  steps:
  - name: Set up Homebrew
    uses: Homebrew/actions/setup-homebrew@04a6d8cfe9d251e2afb78c5bdc6274ec9642aea2 # master

  - name: Install UDS CLI
    shell: bash
    run: |
      brew tap defenseunicorns/tap
      brew install uds
