name: setup-from-previous
description: grabs artifact from a previous job and sets up the env for tests

runs:
  using: composite
  steps:
    # Checkout the repo and setup the tooling for this job
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0

    - name: Download build artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: build-artifacts
        path: build/

    - name: Setup golang
      uses: ./.github/actions/golang

    - name: Make UDS-CLI executable
      shell: bash
      run: |
        chmod +x build/uds

    - name: Setup K3d
      uses: ./.github/actions/k3d
