# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: setup-from-previous
description: grabs artifact from a previous job and sets up the env for tests

inputs:
  setup-k3d:
    description: Whether to setup K3d
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: build-artifacts
        path: build/

    - name: Setup golang
      uses: ./.github/actions/golang

    - name: Make UDS-CLI executable
      shell: bash
      run: |
        chmod +x build/uds

    - name: Setup K3d
      if: ${{ inputs.setup-k3d == 'true' }}
      uses: ./.github/actions/k3d
