# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Dependency Review
on: pull_request

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Dependency Review
        uses: actions/dependency-review-action@ce3cf9537a52e8119d91fd484ab5b8a807627bf8 # v4.6.0
        with:
          fail-on-severity: high
  grype-scan:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - uses: anchore/scan-action@7c05671ae9be166aeb155bad2d7df9121823df32 # v6
          id: scan
          with:
            path: "."
            fail-build: true
            severity-cutoff: high
            output-format: json
            output-file: "grype-scan.json"

        - name: Output Grype Scan Report
          if: always()
          # file name 'grype-scan.json' is defined in .grype.yaml
          run: jq . grype-scan.json

        - name: Upload Grype Scan Report
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
          if: always()
          with:
            name: grype-scan-report
            path: grype-scan.json
            retention-days: 10
            overwrite: "true"
  govulncheck:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Get Go version
          run: sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV

        - id: govulncheck
          uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
          with:
            go-version-input: "${{ env.GO_VERSION }}"
            output-file: govulncheck.txt

        - name: Upload Govulncheck Report
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
          with:
            name: govulncheck-report
            path: govulncheck.txt
            retention-days: 10
            overwrite: "true"
