# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Nightly Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" ## nightly at 3am UTC

permissions:
  contents: read

jobs:
  test:
    permissions:
      packages: write
    uses: ./.github/workflows/release-tests.yaml

  push:
    runs-on: ubuntu-latest
    environment: release-nightly
    needs: test
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-tags: 'true'

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install UDS CLI
        uses: ./.github/actions/install-uds-cli

      - name: Build binary artifacts
        run: |
          uds run build-all

      - name: Rename artifacts for readability
        run: |
          mv build/uds build/uds-nightly-linux-amd64
          mv build/uds-arm build/uds-nightly-linux-arm64
          mv build/uds-mac-apple build/uds-nightly-darwin-arm64
          mv build/uds-mac-intel build/uds-nightly-darwin-amd64

      - name: Update nightly-unstable tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          # cleanup old release
          gh release delete nightly-unstable --cleanup-tag -y || true
          # generate new release
          gh release create nightly-unstable ./build/* \
            -t "nightly-unstable" \
            --prerelease \
            -n 'Nightly unstable build'
