name: Nightly Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' ## Every day at midnight UTC

permissions:
  contents: read

jobs:
#  test:
#    permissions:
#      packages: write
#    uses: ./.github/workflows/release-tests.yaml

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0

    - name: Setup golang
      uses: ./.github/actions/golang

    - name: Install UDS CLI
      uses: ./.github/actions/install-uds-cli

    - name: Build CLI
      run: |
        uds run build-cli-linux-amd

    # Upload the contents of the build directory for later stages to use
    - name: Upload build artifacts
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: build-artifacts
        path: build/
        retention-days: 1
  push:
    runs-on: ubuntu-latest
    environment: release-nightly
#    needs: test
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: Download build artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: build-artifacts
          path: build/

      - name: Create tag
        run: |
          ./hack/create-nightly-tag.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip validate --verbose --config .goreleaser-nightly.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
