name: Nightly Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" ## Every day at midnight UTC

permissions:
  contents: read

jobs:
#  test:
#    permissions:
#      packages: write
#    uses: ./.github/workflows/release-tests.yaml

  push:
    runs-on: ubuntu-latest
    environment: release-nightly
#    needs: test
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-tags: 'true'

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install UDS CLI
        uses: ./.github/actions/install-uds-cli

      - name: Build binary artifacts
        run: |
          uds run build-all

      # ssh into runner
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Update nightly-unstable tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          # cleanup old release
          gh release delete nightly-unstable --cleanup-tag -y || true
          # generate new release
          gh release create nightly-unstable './build/*' \
            -t "nightly-unstable" \
            --prerelease \
            -n 'Nightly unstable build'
