# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Nightly Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" ## nightly at 3am UTC

permissions:
  contents: read

jobs:
  test:
    permissions:
      packages: write
    uses: ./.github/workflows/release-tests.yaml

  push:
    runs-on: ubuntu-latest
    environment: release-nightly
    needs: test
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-tags: 'true'

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Setup release ENV vars
        run: |
          K8S_MODULES_VER=$(go list -f '{{.Version}}' -m k8s.io/client-go | sed 's/v//; s/\./ /g')
          echo K8S_MODULES_MAJOR_VER=$(expr $(echo "$K8S_MODULES_VER" | cut -d " " -f 1) + 1) >> $GITHUB_ENV
          echo K8S_MODULES_MINOR_VER=$(echo "$K8S_MODULES_VER" | cut -d " " -f 2) >> $GITHUB_ENV
          echo K8S_MODULES_PATCH_VER=$(echo "$K8S_MODULES_VER" | cut -d " " -f 3) >> $GITHUB_ENV

          echo K9S_VERSION=$(go list -f '{{.Version}}' -m github.com/derailed/k9s) >> $GITHUB_ENV
          echo CRANE_VERSION=$(go list -f '{{.Version}}' -m github.com/google/go-containerregistry) >> $GITHUB_ENV
          echo SYFT_VERSION=$(go list -f '{{.Version}}' -m github.com/anchore/syft) >> $GITHUB_ENV
          echo ARCHIVES_VERSION=$(go list -f '{{.Version}}' -m github.com/mholt/archives) >> $GITHUB_ENV
          echo HELM_VERSION=$(go list -f '{{.Version}}' -m helm.sh/helm/v4) >> $GITHUB_ENV

      - name: Build release artifacts
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot --skip=homebrew,sbom --config .goreleaser.yaml

      - name: Stage release artifacts
        run: |
          mkdir build
          jq -r '.[] | select((.type == "Binary" and .extra.Format == "binary") or .type == "Linux Package" or .type == "Checksum") | .path' dist/artifacts.json |
            while IFS= read -r artifact_path; do
              cp "$artifact_path" build/
            done

      - name: Update nightly-unstable tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          # cleanup old release
          gh release delete nightly-unstable --cleanup-tag -y || true
          # generate new release
          gh release create nightly-unstable ./build/* \
            -t "nightly-unstable" \
            --prerelease \
            -n 'Nightly unstable build'
