# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Release UDS-CLI on Tag

permissions:
  contents: read

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    if: ${{ !contains(github.ref_name, '-nightly+') && !contains(github.ref_name, '-adhoc+') }}
    uses: ./.github/workflows/test-release.yaml
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit

  publish:
    if: ${{ !contains(github.ref_name, '-nightly+') && !contains(github.ref_name, '-adhoc+') }}
    needs: test
    uses: ./.github/workflows/release-publish.yaml
    permissions:
      contents: write
      packages: write
    with:
      tag_name: ${{ github.ref_name }}
      goreleaser_config: .goreleaser.yaml
      environment: release
      homebrew: true
    secrets: inherit
