# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Test Shim

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  docs-link-check:
    name: Docs Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  build:
    name: Build UDS CLI
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  next-integration-tests:
    name: Next / Integration
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  next-integration-library-tests:
    name: Next / Integration Library
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  next-cluster-tests:
    name: Next / Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  e2e-bundle:
    name: Legacy / E2E Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  e2e-deploy-flags:
    name: Legacy / E2E Deploy Flags
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  e2e-index:
    name: Legacy / E2E Bundle Index
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  e2e-dev:
    name: Legacy / E2E Dev
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  e2e-variable:
    name: Legacy / E2E Variables
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  e2e-optional-bundle:
    name: Legacy / E2E Optional Bundles
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  e2e-vendor-tests:
    name: Legacy / E2E Vendor and Completion
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"

  e2e-engine-tests:
    name: Legacy / E2E Engine
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "skipped"
