# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: E2E PR Tests
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.mdx"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - docs/**
      - .vscode/**
      - .gitignore
      - renovate.json
      - CODEOWNERS
      - LICENSE
      - hack/generate-docs.sh
      - hack/test-docs.sh

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-k3d-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/parallel-tests.yaml
