name: E2E Tests
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
      - "goreleaser.yml"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-k3d-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      # Checkout the repo and setup the tooling for this job
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install UDS CLI
        uses: ./.github/actions/install-uds-cli

      - name: Build CLI
        run: |
          uds run build-cli-linux-amd

      # Upload the contents of the build directory for later stages to use
      - name: Upload build artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: build-artifacts
          path: build/
          retention-days: 1
  test-bundle:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: setup-using-previous-job
        uses: ./.github/actions/setup-from-previous

      - name: Run e2e tests
        run: |
          build/uds run test:run-bundle-test --no-progress

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs

  dev-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: setup-using-previous-job
        uses: ./.github/actions/setup-from-previous

      - name: Run e2e tests
        run: |
          build/uds run test:run-dev-test --no-progress

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs

  test-variables:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: setup-using-previous-job
        uses: ./.github/actions/setup-from-previous

      - name: Run e2e tests
        run: |
          build/uds run test:run-variable-test --no-progress

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs

  test-optional-bundle:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: setup-using-previous-job
        uses: ./.github/actions/setup-from-previous

      - name: Run e2e tests
        run: |
          build/uds run test:run-optional-bundle-tests --no-progress

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs

  test-vendor:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: setup-using-previous-job
        uses: ./.github/actions/setup-from-previous

      - name: Run e2e tests
        run: |
          build/uds run test:run-vendor-tests --no-progress

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
