name: Test K3d Cluster
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-k3d-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install Zarf
        uses: ./.github/actions/zarf

      - name: Build UDS-CLI binary
        run: make build-cli-linux-amd ARCH=amd64

      - name: Setup K3d
        uses: ./.github/actions/k3d

      - name: Run tests
        run: make test

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
